### ISSUE TITLE
Suggestion - tell buyers about sim plans

### ISSUE THREAD

**Issue by gitcnd** [QuickSpot/walter-documentation#1]
Your crowdsupply project looks exciting.

Everyone new to this has no idea about the costs (worse - probably think it costs $$$ per month to have) - you should educate them, or better still, possibly do a deal to include a SIM with purchases?

$15 one-off for 10 years of global coverage (see below) - those are the kinds of numbers that heaps of people do not seem to know about, but which make buying gear which uses these *very* compelling!

These look interesting (I've got both, not tested yet):

https://shop.1nce.com/en

 https://www.thingsmobile.com/business/plans/overview

Also - have you considered squeezing an SD card slot on the underside, opposite the SIM slot?  It seems a shame to waste that important feature when the space to accommodate it on the board looks totally free and easy?  (I don't see the point of having an SD on the expansion harness - the main board is vastly more important for that - especially for critical data-logging situations and data backup etc)

**Comment by gitcnd** [comment]
Also - might be worth considering support for 5ghz wifi6 ?

Chips seem available now: https://www.aliexpress.com/item/1005005664356453.html

**Comment by daanpape** [comment]
Hi @gitcnd, thank you for your suggestions. I definitely like the fact that we should give better insights in the cost of cellular IoT and the fact that it should not be expensive. In our latest newsletter (https://quickspot.io/newsletters/nov-2023.html) we have announced our partnership with Soracom as the preferred SIM card provider. So I can work with them to give better insights on this. This will certainly include the possibility to buy a SIM card together with Walter without having to buy the devkit.

As for the hardware suggestion, we have not placed a micro-SD card there for two reasons:
  1. We wanted to keep enough pins available for the application without restrictions. If we would connect an SD slot than some pins would not be uniquely available for the end-user application.
  2. SD-cards are in 99% of the time additions that need to be installed by the end-user of the product. Having an SD card at the bottom of Walter would not allow this kind of usage.
  
 The Walter hardware is now fully finished and certification is taking place as we speak, so at this point in time we cannot make any hardware adjustments.

**Comment by gitcnd** [comment]
The absolute cheapest Soracom plan is 5 *times* more expensive that either of the ones I mentioned, with the extra drawback that it requires monthly billing and all the devops dangers and admin pain that comes with those fragile systems.

Huge shame about the SD card.  SD card slots use zero pins when no SD is inserted, so your #1 excuse is plain wrong (not to mention pointless; there's vastly more spare pins than anyone could know what to do with already), and #2 makes no sense: whoever already has to install the antennas and/or install the device itself is obviously and literally in the place to install any necessary or optional SD card too.  Even the idea of using this as a SOM is sketchy? - if it can't be laid flat on someone else's PCB and soldered there around the edges, it's just another expensive and complicated non-standard component that needs a pile of extra mechanical PitA to use?

Also a pity about the 5ghz/wifi6

Serious business question: There's already plenty of LTE-M boards that anyone can buy right now off aliexpress - some including SD cards and even included battery holders, and none of which need an extra carrier to use... and if you factor in the extra cost of your "preferred SIM", they're all actually *free* (cost way less than the amount of extra money that your cheapest "preferred" SIM costs over other popular choices), so why would anyone get yours, when it offers less and costs more than what already exists ?

That sounds mean and rude I know - but imagine yourself in 2 or 3 years time form now, having worked huge hours for years on a project that never paid you any profit.  IT is always worth trying to look at your own potential mistakes *before* you make them! Who knows, maybe this paragraph might save you from future financial disasters?

wifi6, and an sd card, would cost you no more than $1 or $2 to add, and bring you an actual advantage, and unless your sim people are paying you upwards of $30 in commission for new customers, dropping them and pitching affordable ones instead would save us end users more than the cost of the board...  maybe you've never bought an LTE-M module before?  The *first* thing most people want to know is the cost of the data, and you've possibly shot yourself in the foot right there.

Just some thoughts for you to hopefully think about!  Don't shoot the messenger!!

**Comment by daanpape** [comment]
Hi Drake,

I definitely won't shoot the messenger :) We have chosen Soracom because of the added value like:

- Good low power support with open and accessible eDRX and PSM settings and good agreements
- Virtual private APN which allows you to talk back to your IoT devices without continuously polling
- Very good packet debugging support like live packet capturing, ...

I do want to stipulate that we are in no way locking Walter to work only with Soracom. The modem is certified for Worldwide use and we have tested Walter with Soracom, 1NCE, TruPhone, Vodacom, AT&T, Telenet, Orange, Proximus, ... There are definately use cases where the 10 EUR for 500Mb over 10 year proposition from 1nce is a good option and we are in no way hiding these options.

Concerning the WiFi6: we have not chosen the ESP32-C6 module because of the following reasons:
 - There are much less I/O pins and we wanted to have the pins available for the end user application.
 - The WiFi 6 is still in the 2.4GHz band, so the only advantage is the OFDMA and TWT feature. TWT would have been a nice to have but in our opinion not a dealbreaker. I also notice that TWT and OFDMA are not always enabled by default in routers.
 - There are no modules with PSRAM and there is no 16MB flash module. The 16MB flash is especially handy for dual partition OTA bootloaders.

Concerning the formfactor I want to say that we have designed it to be 100% compatible with the former PyCom GPy. The THT mounting of the board doesn't cause excessive costs in mass production. This module is not designed to be used in products which have production volumes bigger than 100k per year. In such high production volumes it will be more cost effective to go fully custom. The THT method is also required by the SIM slot at the bottom.

Concerning the SD-card, I just explained our design choice, it is not an excuse. An SD-card slot needs some TVS diodes, termination resistors and also pull-up resistors. These could potentially be in the way of the end user if not used for the SD-card connection. 

Kind regards,
Daan
