### ISSUE TITLE
What type of SIM can be used in Walter?

### ISSUE THREAD

**Issue by mikcatta** [QuickSpot/walter-documentation#4]
Does it need to support a specific variant of 4G or will a standard 4G sim work as well?

**Comment by daanpape** [comment]
Hi @mikcatta,

Walter has an LTE-M and NB-IoT modem on board, you will need a SIM card that supports these network technologies. Most regular SIM cards do not albeit there are some exceptions where a standard SIM card does support LTE-M (when the operator is still on 3GPP rel. 13). So you can definitely try to test with a regular SIM card. If that doesn't work you can use any IoT SIM card. 

These SIM cards are easy to buy as a company but not as a private individual. This last issue was solved by us in co-operation with Soracom and we can offer IoT SIM cards with global coverage to individuals and businesses through our webshop: https://shop.dptechnics.com/

Please let me know in which country you want to connect so that I can verify which technology and providers are offering IoT networks.

**Comment by mikcatta** [comment]
Thank you Daan, I am in the UK. I presume Walter has no option to fall-back to a standard 4G SIM?

**Comment by daanpape** [comment]
Hi Mike,

No, given the structure of cellular networks there is no LTE Cat 1 fallback as this would make the modem a lot more expensive. As you are based in the UK you can directly buy from Soracom both as an individual and company. For this you can use this link: https://auth.soracom.io/signup/console#/

Best regards,
Daan

**Comment by mikcatta** [comment]
SIM has been ordered

**Comment by mikcatta** [comment]
SIM from Soracom has been ordered

**Comment by mikcatta** [comment]
Is there a community for Walter to ask questions... particularly keen to know if anyone has Vodafone NB-IoT working in the UK?

**Comment by daanpape** [comment]
Hi @mikcatta we are currently focusing on Github issues for all Walter related questions. Hosting a community forum is quite a heafty task if you want to keep the forum without spam. We also actively monitor reddit and we are working on a Discord channel (https://discord.gg/RH7qCfRmkx).
