### ISSUE TITLE
Testpoint picture incomplete

### ISSUE THREAD

**Issue by felmue** [QuickSpot/walter-documentation#5]
Hi guys

the picture _img/walter-testpoints.svg_ embedded into [hardware_walter.md](https://www.quickspot.io/documentation.html#/hardware_walter?id=test-pins) is incomplete. The top view is missing the last row and the bottom view is missing completely.

Thanks
Felix

**Comment by daanpape** [comment]
Hi @felmue,

Thank you for pointing this out. Could you please post a screenshot of the image that you see? On our browser it looks like this:

![image](https://github.com/user-attachments/assets/c1fba263-1da6-49b6-a4b0-e80d613757e4)

which does include all pins. 

Best regards,
Daan

**Comment by felmue** [comment]
Hello Daan

interesting. Here is what I see with Firefox on Ubuntu.

Thanks
Felix
![WalterTestpointsFirefox_20240910](https://github.com/user-attachments/assets/dc79a457-72c3-457b-8727-b57f2bc1fc74)

**Comment by daanpape** [comment]
Hi @felmue,

I went to investigate this and it turns out that Firefox has a history of not very well supporting SVG images. I was finally able to fix the issue by re-creating the SVG image from scratch. The issue should therefore now be fixed. Thank you again for pointing this out.

Best regards,
Daan

**Comment by felmue** [comment]
Hello Daan

yes, I can confirm it is fixed.

Thanks
Felix
